### ISSUE TITLE
Publish as Chrome extension?

### ISSUE THREAD

**Issue by jecfish** [PeterNgTr/codeceptjs-recorder-extension#1]
Hi Peter,

Great work on the extension! If you plan to publish to the Chrome Web Store, you can send a PR to mention your extension in https://developer.chrome.com/docs/devtools/recorder/reference/#recorder-extension, and https://github.com/puppeteer/replay#create-a-chrome-extension-for-recorder-available-from-chrome-104-onwards

Cheers,
Jecelyn form the Chrome DevTools team.

**Comment by kobenguyent** [comment]
Thanks @jecfish for the message!

**Comment by kobenguyent** [comment]
hi @jecfish may you guide me on this? It is published as Chrome extension https://chrome.google.com/webstore/detail/codeceptjs-chrome-recorde/ojkfinikejhpchjenhafdlcmgaiaaclg/related?hl=de but it seems not working, it was working fine. Not sure if something is changed with Chrome 🤔

**Comment by jecfish** [comment]
Interesting, as of what I know, there's no changes impact the extension. (e.g. the [Nightwatch Recorder extension](https://chrome.google.com/webstore/detail/nightwatch-chrome-recorde/nhbccjfogdgkahamfohokdhcnemjafjk/) is working fine. 

Can you try to republish and see if you get any error messages?

**Comment by kobenguyent** [comment]
thank you @jecfish it's working now https://chrome.google.com/webstore/detail/codeceptjs-chrome-recorde/jgdcobhagdbipacidhfnoaccgjooebam/related I just forgot to build the extension before loading it with chrome.

**Comment by jecfish** [comment]
Nice, congrats! 🎉

Drop us a PR to get mentioned: 
- https://github.com/puppeteer/replay#create-a-chrome-extension-for-recorder-available-from-chrome-104-onwards
- https://developer.chrome.com/docs/devtools/recorder/reference/#recorder-extension (github [link](https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/en/docs/devtools/recorder/reference/index.md))

**Comment by kobenguyent** [comment]
Thanks @jecfish 
- https://github.com/GoogleChrome/developer.chrome.com/pull/5126
